// -*- adoc -*-
// vim: set syntax=asciidoc:

= Erlog
Robert Virding et al
:Author Initials: RV
:title: Erlog, a prolog that runs in an erlang process
:description: The Erlang VM supports the prolog programming language.
:footer: Logic programming for the better good!
:brand: erlog
:doctype: article
:toc2:
:backend: bootstrap-docs
:link-assets:
:glyphicons: http://glyphicons.com[Glyphicons]

== Overview

Erlog is an implementation of ISO Prolog that can run in an Erlang
process, as such it is ideally suited for adding logical infrences to
a larger Erlang program (Including LFE and elixir programs). 


== Erlog vs SWI Prolog

Erlog is not as full featured or robust as SWI Prolog (or other
prologs). If you want to learn prolog or do a general prolog
application we suggest using SWI Prolog. 

Erlog will excel where close interactions between erlang and prolog
are needed, or where you can take advantage of the erlang process
model to run lots of processes at once.

== Limitations


== Philosophy






== Features


== Documentation


== Roadmap


== Enhancements






== Surprises


== Support


== Copyright and License


------------
The MIT License

Copyright (C) 2013-2014 by Joseph Wayne Norton <norton@alum.mit.edu>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
------------

[bibliography]
== Resources


// -EOF-
